version: '3.9'

services:
  database:
    image: postgres
    container_name: postgres_desafio
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_desafio
    volumes:
      - pgdata:/data/postgres


volumes:
  pgdata:
    driver: local