POST http://localhost:3333/cadastrar
Content-Type: application/json

{
  "name": "pipoca",
  "email": "email@email.com",
  "password": "123456"
}



###
POST http://localhost:3333/entrar
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "123456"
}

#####

POST http://localhost:3333/task
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlNGVmN2VmOC1mOWM3LTQwYjctODgwYS1lYmExZDMwNzFmNGMiLCJpYXQiOjE2ODQyNDc5MTcsImV4cCI6MTY4NDMzNDMxN30.q50fwtmJiUAQxHK3vN-qX5cTi05gOWVrwJy6Na36_1c

{
  "task": "task é obrigatoria",
  "priority": "normal",
  "status": "open"
}

#### GET task-search
GET http://localhost:3333/task-search
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlNGVmN2VmOC1mOWM3LTQwYjctODgwYS1lYmExZDMwNzFmNGMiLCJpYXQiOjE2ODQyNDc5MTcsImV4cCI6MTY4NDMzNDMxN30.q50fwtmJiUAQxHK3vN-qX5cTi05gOWVrwJy6Na36_1c

{
  "task": "teste"
}

#### POST create user teste new router
POST http://localhost:3333/user
Content-Type: application/json

{
  "name": "pipoca",
  "email": "email@email.com",
  "password": "123456"
}

### POST enter user teste new router
POST http://localhost:3333/user-tra
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "123456"
}

### POST create task new routes
POST http://localhost:3333/task-new
Content-Type: application/json

{
  "task": "task é obrigatório",
  "priority": "low",
  "status": "doing",
  "idUser": "e4ef7ef8-f9c7-40b7-880a-eba1d3071f4c"
}

### GET all
GET http://localhost:3333/task-new-get-all?idUser=e4ef7ef8-f9c7-40b7-880a-eba1d3071f4c
Content-Type: application/json /task-new-delete/:id


### Delete
DELETE http://localhost:3333/task-new-delete/f623fc63-d129-4f79-9f31-f1994f3a18d9
Content-Type: application/json


