POST http://localhost:3333/cadastrar
Content-Type: application/json

{
  "name": "pipoca",
  "email": "email@email.com",
  "password": "123456"
}



###
POST http://localhost:3333/entrar
Content-Type: application/json
Authorization: Bearer teste.teste.teste

{
  "email": "email@email.com",
  "password": "123456"
}
